version: '3'

services:
  blue:
    build: ./Blue-Code
    container_name: blue_app
    ports:
      - "8081:80"

  green:
    build: ./Green-code
    container_name: green_app
    ports:
      - "8082:80"

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
